name: Deploy to Production

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*"
      - "src/**"
      - "public/**"
      - "package.json"
      - "tsconfig.json"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Transfer Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          source: "dist/,public/,package.json,package-lock.json,.env.prod"
          target: "/var/www/html/${{ secrets.PROD_FOLDER }}"

      - name: Rename .env.prod to .env
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          script: |
            mv /var/www/html/${{ secrets.PROD_FOLDER }}/.env.prod /var/www/html/${{ secrets.PROD_FOLDER }}/.env

      - name: Start/Restart Application with PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          script: |
            cd /var/www/html/${{ secrets.PROD_FOLDER }}
            npm install --only=production
            pm2 start dist/server.js --name onmangeou || pm2 restart onmangeou
      
      - name: Restart Apache server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          script: |
            sudo systemctl restart apache2