name: Deploy to Production

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*"
      - "front/**"
      - "back/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Transfer Back Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          source: "*"
          target: "/var/www/html/${{ secrets.PROD_FOLDER }}"

      - name: Install Dependencies and Restart node server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          script: |
            cd /var/www/html/${{ secrets.PROD_FOLDER }}
            npm install --only=production
            pm2 start main.js --name onmangeou || pm2 restart onmangeou

      - name: Restart Apache server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_PRIVATE_KEY }}
          script: |
            sudo systemctl restart apache2